### ISSUE TITLE
Feasibility check: live viewing?

### ISSUE THREAD

**Issue by gijs** [tudelft3d/matahn#1]
Hi,

This is a great project, it should be the default interface to the AHN2 data.

Would it be possible to integrate something like [plas.io](https://github.com/verma/plasio) or [potree](http://potree.org/) to enable (semi-) live/instant viewing of the data selection in the browser?

I can imagine certain preprocessing steps would be needed like pyramidizing the AHN2 data into lower-LOD tiles for preview purposes. Maybe it's just too much data anyway?

Gijs

**Comment by Ylannl** [comment]
That is a good idea. Probably the most feasible right now would be to make a button that opens the generated .laz  file in a plas.io viewer. It should be fairly easy to setup, although I haven't looked into the details yet. 

A true live view of the whole (or a portion of the) AHN2 dataset would be great, but might require a duplication of the AHN2 dataset on the server into something that is optimised for adaptive-LOD viewing (for example the octree solution used in potree). This is also an interesting development on this front:  [greyhound](https://github.com/hobu/greyhound). Anyway I'm speculating that any such solution would be very resource hungry (cpu, storage, network). We currently don't have that resources.

If you're willing to do your own preprocessing you might be interested in [LidarViewer](http://doc-ok.org/?p=432), which is the best massive point cloud viewer that I know.

**Comment by gijs** [comment]
Thanks for thinking out loud :) 
Didn't know about greyhound, looks interesting indeed.
