### ISSUE TITLE
Problem running server

### ISSUE THREAD

**Issue by squeakus** [tudelft3d/matahn#4]
hi,
I have spent the last few days setting up and testing my flask/werkzeug environment. I have downloaded sample code and both environments seem to be set up correctly and running. I have started celery and when I start the server it is calling the make_celery(app) function. Unfortunately every time I access the server on localhost it returns the following error:

internal 500 error. The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

More precisely it seems to be a problem with something being passed to werkzeug:
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 641, in **call**
    return app(environ, start_response)
TypeError: 'NoneType' object is not callable

I checked the environ and start response variables and they have been populated:
env: 
{'wsgi.multiprocess': False, 'SERVER_SOFTWARE': 'Werkzeug/0.9.4', 'SCRIPT_NAME': '', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/favicon.ico', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': '', 'werkzeug.server.shutdown': <function shutdown_server at 0x7f611f905938>, 'CONTENT_LENGTH': '', 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36', 'HTTP_CONNECTION': 'keep-alive', 'SERVER_NAME': '127.0.0.1', 'REMOTE_PORT': 55061, 'wsgi.url_scheme': 'http', 'SERVER_PORT': '5000', 'wsgi.input': <socket._fileobject object at 0x7f611f9022d0>, 'HTTP_HOST': 'localhost:5000', 'wsgi.multithread': False, 'HTTP_ACCEPT': '_/_', 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f6129aeb1e0>, 'REMOTE_ADDR': '127.0.0.1', 'HTTP_ACCEPT_LANGUAGE': 'en-GB,en;q=0.8,en-US;q=0.6', 'CONTENT_TYPE': '', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch'}
start_response:
<function start_response at 0x7f611f905c08>

I think it may be a problem with my config file. I assumed the tasks and results folder could point anywhere, maybe I am wrong about this?
TASKS_FOLDER    = '/home/jonathan/tmp/'
RESULTS_FOLDER  = '/home/jonathan/tmp/'

also I am running this locally so I left the server name as example.com. Should I change it to something different if I am running it on the localhost?

My apologies for all the questions and thank you for your help so far.

**Comment by Ylannl** [comment]
You should set the server name to `localhost:5000`.  But I'm not sure if that will fix this issue. 
The `TASKS_FOLDER` is actually not used anymore, so that shouldn't matter.

**Comment by squeakus** [comment]
I tried your fix on friday and now it can detect the server, thanks for your prompt reply. It still seems to be using the tasks folder as each selection is dumping out the laz file in my tmp folder.

**Comment by Ylannl** [comment]
Good to hear that! That file is probably dumped in `/tmp` because you set your `RESULTS_FOLDER` to that folder as well.

I'm guessing now that the built-in Netherlands-only map layers are useless to you. Please let me know if there are any other issues.

**Comment by squeakus** [comment]
Hi Ravi,
you are absolutely right about the map layers but I don't want to keep
plaguing you with question and I want to dig a little deeper into the code.
There are also some other questions I have (why redis, why postgresql) but
let me bash my head against it for another couple of days and see if I make
some progress myself. Thank you for all your help, if you ever find
yourself in Ireland I owe you several pints!
